language: csharp
mono: none
dotnet: 2.1.3
script:
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./build.sh BuildAndPublish; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./build.sh; fi'
branches:
  only: 
    - test
