pool:
  name: Hosted Windows 2019 with VS2019

trigger:
  branches:
    include:
    - master2
  paths:
    include:
    - infrastructure/ArmTemplates/SearchService/*

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/infrastructure/ArmTemplates/SearchService'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: # (no value); this input is optional

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
    artifactName: BuildOutput